path: E:/API/Yolov8/ultralytics/data  # dataset root dir
train: images/train  # train images (relative to 'path')
val: images/train  # val images (relative to 'path')

# Classes
# names:
#   0: alpaca
nc: 10
names: 
  0: bicycle 
  1: bird
  2: bus
  3: car
  4: cat
  5: dog
  6: fox
  7: package
  8: person
  9: truck